// <auto-generated />
using System;
using ClassSchedule.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ClassSchedule.Domain.Entities.Timetable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FirstMonday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("ClassSchedule.Domain.Entities.Timetable", b =>
                {
                    b.OwnsMany("ClassSchedule.Domain.Entities.Course", "Courses", b1 =>
                        {
                            b1.Property<Guid>("TimetableId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Note")
                                .HasColumnType("TEXT");

                            b1.HasKey("TimetableId", "Id");

                            b1.ToTable("Course");

                            b1.WithOwner()
                                .HasForeignKey("TimetableId");

                            b1.OwnsMany("ClassSchedule.Domain.Entities.Fragment", "Fragments", b2 =>
                                {
                                    b2.Property<Guid>("CourseTimetableId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("CourseId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Location")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Period")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Teacher")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Weekday")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Weeks")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("CourseTimetableId", "CourseId", "Id");

                                    b2.ToTable("Fragment");

                                    b2.WithOwner()
                                        .HasForeignKey("CourseTimetableId", "CourseId");
                                });

                            b1.Navigation("Fragments");
                        });

                    b.OwnsMany("ClassSchedule.Domain.Entities.PeriodDefinition", "PeriodDefinitions", b1 =>
                        {
                            b1.Property<Guid>("TimetableId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("TimetableId", "Ordinal");

                            b1.ToTable("PeriodDefinition");

                            b1.WithOwner()
                                .HasForeignKey("TimetableId");
                        });

                    b.Navigation("Courses");

                    b.Navigation("PeriodDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
